serve:
  port: 8081
  mode: debug

datasource:
  postgres:
    dsn: postgres://postgres:root@47.110.74.7:5432/mini_blog?sslmode=disable&TimeZone=Asia/Shanghai
  redis:
    addr: 47.110.74.7:6379
    db: 0